### ISSUE TITLE
Error: libuvc.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by froston** [ghafran/ptz#1]
I followed the install instruction on linux and got this error when importing the lib in `index.js`

`var ptz = require('ptz')`
```
> node index.js

internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libuvc.so.0: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/froston/dev/ptz-cam/node_modules/ptz/lib/ptz.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/froston/dev/ptz-cam/index.js:1:73)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```
Any ideas what the iisue could be? Thanks!

**Comment by froston** [comment]
FIxed it running `sudo /sbin/ldconfig -v`
